name: CI
on: 
  push:
    branches-ignore:
      - docs
jobs:
  run:
    name: Build and Run
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          cache: sbt
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: Run the unit tests
        run: sbt test