name: Generate Scaladoc and deploy to GitHub Pages
on:
  push:
    branches:
      - docs
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          cache: sbt
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Build Markdown with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: Generate Scaladoc
        run: sbt doc
      - name: Merge Scaladoc into the existing site
        run: |
          sudo chown -R $USER:$USER ./_site
          cp -r ./docs/scaladoc ./_site/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
